//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbTool.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbTool.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 生成设置 的本地化字符串。
        /// </summary>
        public static string BuildSettings {
            get {
                return ResourceManager.GetString("BuildSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节数 的本地化字符串。
        /// </summary>
        public static string ByteCount {
            get {
                return ResourceManager.GetString("ByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码优先 的本地化字符串。
        /// </summary>
        public static string CodeFirst {
            get {
                return ResourceManager.GetString("CodeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库优先 的本地化字符串。
        /// </summary>
        public static string DatabaseFirst {
            get {
                return ResourceManager.GetString("DatabaseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库类型 的本地化字符串。
        /// </summary>
        public static string DatabaseType {
            get {
                return ResourceManager.GetString("DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数 的本地化字符串。
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认数据库连接字符串 的本地化字符串。
        /// </summary>
        public static string DefaultDatabaseConnectionString {
            get {
                return ResourceManager.GetString("DefaultDatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认数据库类型 的本地化字符串。
        /// </summary>
        public static string DefaultDatabaseType {
            get {
                return ResourceManager.GetString("DefaultDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认语言 的本地化字符串。
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段名 的本地化字符串。
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件范围命名空间 的本地化字符串。
        /// </summary>
        public static string FileScopedNamespace {
            get {
                return ResourceManager.GetString("FileScopedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部生成 的本地化字符串。
        /// </summary>
        public static string GenerateAll {
            get {
                return ResourceManager.GetString("GenerateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成代码 的本地化字符串。
        /// </summary>
        public static string GenerateCode {
            get {
                return ResourceManager.GetString("GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成数据库描述 的本地化字符串。
        /// </summary>
        public static string GenerateDatabaseDescription {
            get {
                return ResourceManager.GetString("GenerateDatabaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局引用 的本地化字符串。
        /// </summary>
        public static string GlobalReferences {
            get {
                return ResourceManager.GetString("GlobalReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标识 的本地化字符串。
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接字符串 的本地化字符串。
        /// </summary>
        public static string LinkedSymbols {
            get {
                return ResourceManager.GetString("LinkedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改默认配置 的本地化字符串。
        /// </summary>
        public static string ModifyDefaultConfiguration {
            get {
                return ResourceManager.GetString("ModifyDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名空间 的本地化字符串。
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可空引用类型 的本地化字符串。
        /// </summary>
        public static string NullableReferenceTypes {
            get {
                return ResourceManager.GetString("NullableReferenceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前缀 的本地化字符串。
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键 的本地化字符串。
        /// </summary>
        public static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择Model文件 的本地化字符串。
        /// </summary>
        public static string SelectModelFile {
            get {
                return ResourceManager.GetString("SelectModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后缀 的本地化字符串。
        /// </summary>
        public static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表说明 的本地化字符串。
        /// </summary>
        public static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表名 的本地化字符串。
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看代码 的本地化字符串。
        /// </summary>
        public static string ViewCode {
            get {
                return ResourceManager.GetString("ViewCode", resourceCulture);
            }
        }
    }
}
